version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        UID: ${UID?}
        DJANGO_ENV: dev
    env_file: dev.env
    environment:
      - DJANGO_APP_NAME=orchard
      - DJANGO_ENV=dev
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    env_file: dev.env
    environment:
      - POSTGRES_DB=$DJANGO_DB_NAME
      - POSTGRES_USER=$DJANGO_DB_USER
      - POSTGRES_PASSWORD=$DJANGO_DB_PASSWORD
